### ISSUE TITLE
Notification Removed

### ISSUE THREAD

**Issue by Waleed055** [fbiego/NotificationReply#1]
When the reply is automatically sent, whats app' notification is removed from the notification bar?

**Comment by fbiego** [comment]
the notification is removed

https://github.com/fbiego/NotificationReply/blob/ea477f0b25ddf5a1bcaf0090166c1fe42bd605c8/app/src/main/java/com/fbiego/notificationreply/app/NotificationService.kt#L85

**Comment by Waleed055** [comment]
@fbiego Yes, I had already updated my code btw thanks for replying.
